### ISSUE TITLE
Trasig tabell inne på historik?

### ISSUE THREAD

**Issue by datalowe** [fahlstrm/pattern-customerweb#12]
När jag går in på 'historik' så verkar något bli konstigt med tabellen, så att raden vid botten för att välja sida blir alldeles för bred/inte är syncad med raderna i själva tabellen. Det blir likadant både i Firefox och Chrome.

<img width="1280" alt="trasig_tabell" src="https://user-images.githubusercontent.com/65363390/145201679-45c7215b-45cc-4115-96e8-3f07196eba31.png">

**Comment by fahlstrm** [comment]
Kan inte säga vad som skiljer från tabeller i admin - men har manuellt angett bredden för table.

**Comment by fahlstrm** [comment]
Går sönder vid mindre browserfönster istället. 
Stäng om vi godkänner lösningen.
