### ISSUE TITLE
Fontawesome ligger inte som dependency

### ISSUE THREAD

**Issue by jannikarlsson** [fahlstrm/pattern-customerweb#6]
Går inte att starta efter npm install eftersom fontawesome inte kommer med.

**Comment by fahlstrm** [comment]
Var Fortawesome i angular.jsom som spökade.
Borttaget

`            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/purple-green.css",
              "node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/solid.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/regular.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/brands.scss",`
